//! Safe Rust wrapper for the docling-parse C API
//!
//! This crate provides safe, idiomatic Rust bindings to the docling-parse library,
//! which is used for PDF document parsing with advanced text segmentation.
//!
//! # Overview
//!
//! The `docling-parse-rs` crate wraps a C/C++ PDF parsing library, providing:
//!
//! - **Memory-safe access**: RAII-style resource management
//! - **Error handling**: Rust `Result` types for all operations
//! - **Type conversion**: Automatic conversion between C and Rust types
//! - **Thread safety**: `Send` and `Sync` implementations where appropriate
//!
//! # Architecture
//!
//! ```text
//! ┌─────────────────────────────────────────────────────────────┐
//! │                      Rust Application                       │
//! └─────────────────────────────────────────────────────────────┘
//!                              │
//!                              ▼
//! ┌─────────────────────────────────────────────────────────────┐
//! │                     docling-parse-rs                        │
//! │  ┌─────────────┐  ┌─────────────┐  ┌─────────────────────┐  │
//! │  │DoclingParser│  │   convert   │  │       types        │  │
//! │  │  (safe API) │  │  (helpers)  │  │ (Rust data models) │  │
//! │  └─────────────┘  └─────────────┘  └─────────────────────┘  │
//! └─────────────────────────────────────────────────────────────┘
//!                              │
//!                              ▼
//! ┌─────────────────────────────────────────────────────────────┐
//! │                   docling-parse-sys (FFI)                   │
//! │            Raw C bindings generated by bindgen              │
//! └─────────────────────────────────────────────────────────────┘
//!                              │
//!                              ▼
//! ┌─────────────────────────────────────────────────────────────┐
//! │                  docling-parse (C++ library)                │
//! │               PDF parsing and text segmentation             │
//! └─────────────────────────────────────────────────────────────┘
//! ```
//!
//! # Usage
//!
//! ## Basic PDF Parsing
//!
//! ```no_run
//! use docling_parse_rs::DoclingParser;
//!
//! // Create a parser instance
//! let mut parser = DoclingParser::new("error")?;
//!
//! // Load a PDF document with a unique key
//! parser.load_document("my_doc", std::path::Path::new("document.pdf"), None)?;
//!
//! // Get the number of pages
//! let num_pages = parser.number_of_pages("my_doc")?;
//! println!("Document has {} pages", num_pages);
//!
//! // Parse each page
//! for page_num in 0..num_pages {
//!     let page = parser.parse_page("my_doc", page_num)?;
//!     println!("Page {}: {:?}", page_num, page);
//! }
//!
//! // Cleanup (automatically called on drop, but can be explicit)
//! parser.unload_document("my_doc")?;
//! # Ok::<(), Box<dyn std::error::Error>>(())
//! ```
//!
//! ## Structured Page Parsing
//!
//! For integration with docling-core types:
//!
//! ```no_run
//! use docling_parse_rs::DoclingParser;
//!
//! let mut parser = DoclingParser::new("warn")?;
//! parser.load_document("doc", std::path::Path::new("file.pdf"), None)?;
//!
//! // Get structured page data compatible with docling-core
//! let segmented_page = parser.parse_page_structured("doc", 0)?;
//! println!("Page dimensions: {}x{}", segmented_page.width, segmented_page.height);
//! # Ok::<(), Box<dyn std::error::Error>>(())
//! ```
//!
//! ## Password-Protected PDFs
//!
//! ```no_run
//! use docling_parse_rs::DoclingParser;
//!
//! let mut parser = DoclingParser::new("error")?;
//!
//! // Provide password for encrypted PDFs
//! parser.load_document(
//!     "secure_doc",
//!     std::path::Path::new("encrypted.pdf"),
//!     Some("my_password")
//! )?;
//! # Ok::<(), Box<dyn std::error::Error>>(())
//! ```
//!
//! # Modules
//!
//! - [`convert`]: Type conversion utilities (C types → Rust types)
//! - [`error`]: Error types and result aliases
//! - [`types`]: Rust data structures for parsed content
//!
//! # Thread Safety
//!
//! [`DoclingParser`] implements both `Send` and `Sync`, allowing it to be shared
//! across threads. The underlying C++ library uses thread-local storage for
//! internal state.
//!
//! # Error Handling
//!
//! All fallible operations return `Result<T, Error>`. Common error conditions:
//!
//! - [`Error::OutOfMemory`] - Failed to allocate parser
//! - [`Error::NotLoaded`] - Document not found (wrong key)
//! - [`Error::ParseFailed`] - PDF parsing error
//! - [`Error::InvalidParameter`] - Invalid arguments
//!
//! # See Also
//!
//! - [`docling_core`](../docling_core) - Core document types and conversion
//! - [`docling_backend`](../docling_backend) - High-level document processing

mod convert;
mod error;
mod parser;
pub mod types;

pub use convert::{convert_cell_array, convert_dimension, convert_to_segmented_page};
pub use error::{Error, Result};
pub use parser::DoclingParser;
