#!/usr/bin/env python3
"""
Generate diverse OBJ test files for docling_rs integration tests.
Creates 5 different OBJ files with varying complexity and features.
"""

import os
import math

# Output directory
OUTPUT_DIR = "test-corpus/cad/obj"
os.makedirs(OUTPUT_DIR, exist_ok=True)


def generate_simple_cube():
    """
    1. Simple cube - basic geometric primitive (8 vertices, 12 triangular faces)
    """
    content = """# Simple cube - basic geometric primitive
# 8 vertices, 12 triangular faces
# Generated by docling_rs test suite

o Cube
v 0.0 0.0 0.0
v 1.0 0.0 0.0
v 1.0 1.0 0.0
v 0.0 1.0 0.0
v 0.0 0.0 1.0
v 1.0 0.0 1.0
v 1.0 1.0 1.0
v 0.0 1.0 1.0

# Front face
f 1 2 3
f 1 3 4
# Back face
f 5 7 6
f 5 8 7
# Top face
f 4 3 7
f 4 7 8
# Bottom face
f 1 6 2
f 1 5 6
# Right face
f 2 6 7
f 2 7 3
# Left face
f 1 4 8
f 1 8 5
"""
    with open(os.path.join(OUTPUT_DIR, "simple_cube.obj"), "w") as f:
        f.write(content)
    print("✓ Generated simple_cube.obj (8 vertices, 12 triangles)")


def generate_teapot_excerpt():
    """
    2. Teapot excerpt - complex shape with multiple models
    A simplified teapot with body, spout, and handle as separate objects
    """
    content = """# Teapot (simplified) - complex shape with multiple models
# Multiple objects: body, spout, handle
# Generated by docling_rs test suite

o Body
v 0.0 0.0 0.0
v 1.0 0.0 0.0
v 1.5 0.5 0.0
v 1.0 1.0 0.0
v 0.0 1.0 0.0
v -1.0 1.0 0.0
v -1.5 0.5 0.0
v -1.0 0.0 0.0
# Bottom face
f 1 2 3
f 1 3 8
f 8 3 7
# Top face
f 4 5 6
f 4 6 7

o Spout
v 1.5 0.5 0.0
v 2.0 0.6 0.1
v 2.5 0.7 0.2
v 2.5 0.8 0.2
# Spout geometry
f 9 10 11
f 10 11 12

o Handle
v -1.5 0.5 0.0
v -2.0 0.6 0.1
v -2.0 0.8 0.1
v -1.5 0.9 0.0
# Handle geometry
f 13 14 15
f 13 15 16
"""
    with open(os.path.join(OUTPUT_DIR, "teapot_excerpt.obj"), "w") as f:
        f.write(content)
    print("✓ Generated teapot_excerpt.obj (3 objects, 16 vertices, 10 triangles)")


def generate_with_normals():
    """
    3. Model with vertex normals - testing normal handling
    """
    content = """# Pyramid with vertex normals
# Tests normal vector handling
# Generated by docling_rs test suite

o Pyramid
# Base vertices
v 0.0 0.0 0.0
v 1.0 0.0 0.0
v 1.0 0.0 1.0
v 0.0 0.0 1.0
# Apex
v 0.5 1.0 0.5

# Vertex normals (pointing outward)
vn 0.0 -1.0 0.0
vn -0.707 0.707 0.0
vn 0.707 0.707 0.0
vn 0.0 0.707 -0.707
vn 0.0 0.707 0.707

# Base (downward normal)
f 1//1 2//1 3//1
f 1//1 3//1 4//1

# Sides (with normals)
f 1//2 5//2 2//2
f 2//3 5//3 3//3
f 3//4 5//4 4//4
f 4//5 5//5 1//5
"""
    with open(os.path.join(OUTPUT_DIR, "pyramid_with_normals.obj"), "w") as f:
        f.write(content)
    print("✓ Generated pyramid_with_normals.obj (5 vertices, 6 triangles, normals)")


def generate_with_textures():
    """
    4. Model with texture coordinates - testing texcoord handling
    """
    content = """# Textured quad - tests texture coordinate handling
# Generated by docling_rs test suite

mtllib textured_quad.mtl

o TexturedQuad
# Vertices forming a quad
v -1.0 -1.0 0.0
v  1.0 -1.0 0.0
v  1.0  1.0 0.0
v -1.0  1.0 0.0

# Texture coordinates (UV mapping)
vt 0.0 0.0
vt 1.0 0.0
vt 1.0 1.0
vt 0.0 1.0

# Vertex normals (facing forward)
vn 0.0 0.0 1.0

usemtl DefaultMaterial

# Faces with vertex/texture/normal indices
f 1/1/1 2/2/1 3/3/1
f 1/1/1 3/3/1 4/4/1
"""

    # Also create a simple MTL file
    mtl_content = """# Material file for textured_quad.obj
# Generated by docling_rs test suite

newmtl DefaultMaterial
Ka 0.2 0.2 0.2
Kd 0.8 0.8 0.8
Ks 1.0 1.0 1.0
Ns 100.0
d 1.0
illum 2
map_Kd texture.png
"""
    with open(os.path.join(OUTPUT_DIR, "textured_quad.obj"), "w") as f:
        f.write(content)
    with open(os.path.join(OUTPUT_DIR, "textured_quad.mtl"), "w") as f:
        f.write(mtl_content)
    print("✓ Generated textured_quad.obj (4 vertices, 2 triangles, texture coords, material)")


def generate_sphere():
    """
    5. Sphere (icosphere) - moderate complexity test
    Creates a simple icosphere with 12 vertices and 20 triangular faces
    """
    # Golden ratio
    phi = (1.0 + math.sqrt(5.0)) / 2.0

    # 12 vertices of an icosahedron
    vertices = [
        (-1,  phi, 0), ( 1,  phi, 0), (-1, -phi, 0), ( 1, -phi, 0),
        (0, -1,  phi), (0,  1,  phi), (0, -1, -phi), (0,  1, -phi),
        (phi, 0, -1), ( phi, 0,  1), (-phi, 0, -1), (-phi, 0,  1)
    ]

    # Normalize to unit sphere
    vertices = [(x/math.sqrt(x*x+y*y+z*z), y/math.sqrt(x*x+y*y+z*z), z/math.sqrt(x*x+y*y+z*z))
                for x, y, z in vertices]

    # 20 triangular faces of an icosahedron
    faces = [
        # 5 faces around point 0
        (0, 11, 5), (0, 5, 1), (0, 1, 7), (0, 7, 10), (0, 10, 11),
        # Adjacent faces
        (1, 5, 9), (5, 11, 4), (11, 10, 2), (10, 7, 6), (7, 1, 8),
        # 5 faces around point 3
        (3, 9, 4), (3, 4, 2), (3, 2, 6), (3, 6, 8), (3, 8, 9),
        # Adjacent faces
        (4, 9, 5), (2, 4, 11), (6, 2, 10), (8, 6, 7), (9, 8, 1)
    ]

    content = "# Icosphere - 12 vertices, 20 triangular faces\n"
    content += "# Simple sphere approximation\n"
    content += "# Generated by docling_rs test suite\n\n"
    content += "o Icosphere\n"

    # Write vertices
    for x, y, z in vertices:
        content += f"v {x:.6f} {y:.6f} {z:.6f}\n"

    content += "\n"

    # Write faces (OBJ is 1-indexed)
    for a, b, c in faces:
        content += f"f {a+1} {b+1} {c+1}\n"

    with open(os.path.join(OUTPUT_DIR, "icosphere.obj"), "w") as f:
        f.write(content)
    print("✓ Generated icosphere.obj (12 vertices, 20 triangles)")


def main():
    print("Generating OBJ test files...")
    print(f"Output directory: {OUTPUT_DIR}\n")

    generate_simple_cube()
    generate_teapot_excerpt()
    generate_with_normals()
    generate_with_textures()
    generate_sphere()

    print("\n✓ All OBJ test files generated successfully!")
    print(f"  Total: 5 OBJ files + 1 MTL file")


if __name__ == "__main__":
    main()
