//! Raw FFI bindings to the docling-parse C API
//!
//! This crate provides low-level unsafe bindings to the C API wrapper around the
//! `docling-parse` C++ library. The bindings are auto-generated by `bindgen` from
//! the C header file defined in `wrapper.h`.
//!
//! # Overview
//!
//! The `docling-parse` library is a high-performance C++ PDF parsing engine originally
//! developed as part of the Python docling project. This crate exposes its functionality
//! to Rust through FFI, enabling native PDF parsing with:
//!
//! - Text extraction with position information
//! - Table detection and cell extraction
//! - Image and figure detection
//! - Page structure analysis
//!
//! # Architecture
//!
//! ```text
//! ┌─────────────────────────────────────────────────────────────────┐
//! │                      docling-parse-rs                          │
//! │              (Safe Rust wrapper - use this!)                   │
//! └─────────────────────────────────────────────────────────────────┘
//!                               │
//!                               ▼
//! ┌─────────────────────────────────────────────────────────────────┐
//! │                      docling-parse-sys                         │  ← You are here
//! │              (Raw FFI bindings - this crate)                   │
//! └─────────────────────────────────────────────────────────────────┘
//!                               │
//!                               ▼
//! ┌─────────────────────────────────────────────────────────────────┐
//! │                      docling-parse C API                       │
//! │              (C wrapper around C++ library)                    │
//! └─────────────────────────────────────────────────────────────────┘
//!                               │
//!                               ▼
//! ┌─────────────────────────────────────────────────────────────────┐
//! │                   docling-parse C++ Library                    │
//! │              (Core PDF parsing implementation)                 │
//! └─────────────────────────────────────────────────────────────────┘
//! ```
//!
//! # Usage
//!
//! **Prefer the safe wrapper:** Use [`docling-parse-rs`] for a safe, ergonomic API.
//! Only use this crate directly if you need low-level control or are building
//! your own wrapper.
//!
//! # Building
//!
//! This crate requires the docling-parse C++ library to be built first:
//!
//! ```bash
//! # 1. Build the C++ library
//! cd external/docling-parse
//! mkdir build && cd build
//! cmake .. -DCMAKE_BUILD_TYPE=Release
//! make
//!
//! # 2. Set environment variables
//! export DOCLING_PARSE_INCLUDE_PATH=/path/to/docling-parse/include
//! export DOCLING_PARSE_LIB_PATH=/path/to/docling-parse/build
//!
//! # 3. Build the Rust crate
//! cargo build -p docling-parse-sys
//! ```
//!
//! # Safety
//!
//! All functions in this crate are unsafe because they directly call C functions.
//! Callers must ensure:
//! - Pointers are valid and properly aligned
//! - Strings are valid UTF-8 and null-terminated
//! - Memory is freed using the appropriate free functions
//! - Objects are not used after being freed
//!
//! # Generated Bindings
//!
//! The bindings are generated at build time by `bindgen` and include:
//!
//! - `docling_parser_new()` - Create a new parser instance
//! - `docling_parser_free()` - Free a parser instance
//! - `docling_parser_parse_file()` - Parse a PDF file
//! - `docling_parser_parse_bytes()` - Parse PDF from memory
//! - `docling_result_*` - Result access functions
//!
//! See the generated `bindings.rs` in `OUT_DIR` for the complete API.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

// Include the generated bindings
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// Tests only compile when the C++ library is available
// The build.rs creates a stub bindings.rs when the library is not found
#[cfg(all(test, not(doc)))]
mod tests {
    // Only include tests if the bindings contain actual functions
    // (The stub bindings file is empty except for a comment)
    #[cfg(not(any(
        target_os = "none",
        all(not(windows), not(unix))
    )))]
    #[test]
    #[ignore = "Requires C++ library to be built first - see README.md"]
    fn test_parser_lifecycle() {
        // This test is only for when the C++ library is actually built
        // Since we can't conditionally compile based on file content,
        // we mark it as ignored and document that it requires setup

        // Uncomment when library is built:
        // use super::*;
        // use std::ffi::CString;
        // unsafe {
        //     let loglevel = CString::new("error").unwrap();
        //     let parser = docling_parser_new(loglevel.as_ptr());
        //     assert!(!parser.is_null(), "Parser should not be null");
        //     docling_parser_free(parser);
        // }
    }
}
